server:
  port: 9091
  servlet:
    context-path: /k8s
spring:
  data:
    redis:
      host: 192.168.64.3
      port: 30679
      password: admin123
  datasource:
    url: jdbc:h2:./data/auth
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true